### ISSUE TITLE
Hi, what is this fork useful for?

### ISSUE THREAD

**Issue by luzpaz** [AlexandrParkhomenko/FreeCAD#1]
Wandered across this repo. Just wondering why are you maintaining an FC fork ?

**Comment by luzpaz** [comment]
bump

**Comment by AlexandrParkhomenko** [comment]
Excuse me for big time of the answer. People are often busy with various affairs.
I need only the Path module with some 
> Simple is better than complex.

**Comment by AlexandrParkhomenko** [comment]
No response from OP. Closing ticket
